
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				pig = true
				villager = true
				bee = true
				fox = true
				wandering_trader = true
				hopper_minecart = true
				leash_knot = true
				item = true
				experience_orb = true
				item_frame = true
				pillager = true
				minecart = true
				blaze = true
				armor_stand = true
				rabbit = true
				ender_dragon = true
				cow = true
				chicken = true
				sheep = true
				bat = true
				squid = true
				spider = true
				salmon = true
				drowned = true
				creeper = true
				zombie = true
				skeleton = true
				glow_squid = true
				boat = true
				egg = true
				snowball = true
				zombie_villager = true
				zombie_horse = true
				witch = true
				donkey = true
				cod = true
				tropical_fish = true
				dolphin = true
				pufferfish = true
				ender_pearl = true
				endermite = true
				enderman = true
				stray = true
				lightning_bolt = true
				turtle = true
				allay = true
				iron_golem = true
				husk = true
				piglin_brute = true
				piglin = true
				hoglin = true
				zombified_piglin = true
				potion = true
				arrow = true
				axolotl = true

